version: '3.4'

services:
  apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    depends_on:
      - documenttemplate.api

  documenttemplate.api:
    build:
      context: .
      dockerfile: ./DocumentTemplate.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=documenttemplatedb;Port=5432;Database=DocumentTemplateDb;User Id=admin;Password=admin1234;"
    depends_on:
      - documenttemplatedb

  documenttemplatemetadata.api:
    build:
      context: .
      dockerfile: ./DocumentTemplateMetadata.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=documenttemplatedb;Port=5432;Database=DocumentTemplateDb;User Id=admin;Password=admin1234;"
    depends_on:
      - documenttemplatedb

  documenttemplatedb:
    container_name: documenttemplatedb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql_data/data/