version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

  documenttemplate.api:
    image: ${DOCKER_REGISTRY-}documenttemplateapi
    build:
      context: .
      dockerfile: DocumentTemplate/DocumentTemplate.API/Dockerfile

  documenttemplatemetadata.api:
    image: ${DOCKER_REGISTRY-}documenttemplatemetadataapi
    build:
      context: .
      dockerfile: ../DocumentTemplateMetadata.API/DocumentTemplateMetadata.API/Dockerfile

  documenttemplatedb:
    image: postgres

volumes:
   postgres_data:
