version: '3.4'

services:
  apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"

  documenttemplate.api:
    build:
      context: .
      dockerfile: ./DocumentTemplate.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"
